# Generated by Django 4.2.5 on 2023-11-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=True, null=True, verbose_name='is_teacher'),
        ),
    ]
