# Generated by Django 4.2.5 on 2023-11-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_customuser_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assistance_required',
        ),
    ]
